export const SET_POST="setPost"
export const SET_COMMENTS="setComments"
export const SET_POSTS="setPosts"
export const SET_USER="setUser"
export const FETCH_START="setStart"
export const FETCH_END="fetchEnd"
export const SET_ERROR="setError"
export const SET_ITEM_TYPE="setItemType"
export const SET_PAGINATION="setPagination"
export const SET_RESET_PAGINATION="setResetPagination"

